package com.example.driverchecker.machinelearning.helpers.windows

import com.example.driverchecker.machinelearning.data.IImageDetectionOutputStats
import com.example.driverchecker.machinelearning.helpers.windows.factories.ClassificationWindowFactory
import com.example.driverchecker.machinelearning.helpers.windows.factories.IClassificationWindowFactory
import com.example.driverchecker.machinelearning.helpers.windows.singles.AClassificationWindowOld
import com.example.driverchecker.machinelearning.helpers.windows.singles.ClassificationWindowOld
import com.example.driverchecker.machinelearning.helpers.windows.singles.IClassificationWindowOld

typealias ImageDetectionWindow = ClassificationWindowOld<IImageDetectionOutputStats<String>, String>
typealias IImageDetectionWindow = IClassificationWindowOld<IImageDetectionOutputStats<String>, String>
typealias AImageDetectionWindow = AClassificationWindowOld<IImageDetectionOutputStats<String>, String>